name: PR Labeler

on:
  pull_request:
    types: [opened]

jobs:
  needs-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add label to PR
        run: | 
          gh pr edit ${{ github.event.pull_request.number }} --add-label "needs-review"
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}